name: "ESPHome Proxy"
version: "1.4"
panel_icon: "mdi:chip"
panel_title: ESPHome
slug: esphome_proxy
description: Proxy addon for ESPHome
url: "https://github.com/felalex/hass-esphome-proxy"
startup: application
boot: auto
ingress: true
init: false
ingress_port: 6052
panel_admin: false
options:
  server: "esphome.local:6052"
schema:
  server: "match(^.+:\\d+$)"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386